insert into users values(1, 'Jan');
insert into users values(2, 'Robert');
insert into users values(3, 'Mateusz');

insert into weeks values(1, 'CW12');
insert into weeks values(2, 'CW15');
insert into weeks values(3, 'CW18');
insert into weeks values(4, 'CW21');
insert into weeks values(5, 'CW24');
insert into weeks values(6, 'CW27');
insert into weeks values(7, 'CW30');
insert into weeks values(8, 'CW33');
insert into weeks values(9, 'CW36');
insert into weeks values(10, 'CW39');
insert into weeks values(11, 'CW42');
insert into weeks values(12, 'CW45');
insert into weeks values(13, 'CW48');

insert into areas values(1, 'PENDING', 'KCH', 1, 1);
insert into areas values(2, 'PENDING', 'KOR', 2, 1);
insert into areas values(3, 'DONE', 'ŁAZ', 3, 1);
insert into areas values(4, 'INACTIVE', 'ŁAZ', 1, 2);
insert into areas values(5, 'INACTIVE', 'KCH', 2, 2);
insert into areas values(6, 'INACTIVE', 'KOR', 3, 2);
insert into areas values(7, 'INACTIVE', 'KOR', 1, 3);
insert into areas values(8, 'INACTIVE', 'ŁAZ', 2, 3);
insert into areas values(9, 'INACTIVE', 'KCH', 3, 3);
insert into areas values(10, 'INACTIVE', 'KCH', 1, 4);
insert into areas values(11, 'INACTIVE', 'KOR', 2, 4);
insert into areas values(12, 'INACTIVE', 'ŁAZ', 3, 4);
insert into areas values(13, 'INACTIVE', 'ŁAZ', 1, 5);
insert into areas values(14, 'INACTIVE', 'KCH', 2, 5);
insert into areas values(15, 'INACTIVE', 'KOR', 3, 5);
insert into areas values(16, 'INACTIVE', 'KOR', 1, 6);
insert into areas values(17, 'INACTIVE', 'ŁAZ', 2, 6);
insert into areas values(18, 'INACTIVE', 'KCH', 3, 6);
insert into areas values(19, 'INACTIVE', 'KCH', 1, 7);
insert into areas values(20, 'INACTIVE', 'KOR', 2, 7);
insert into areas values(21, 'INACTIVE', 'ŁAZ', 3, 7);
insert into areas values(22, 'INACTIVE', 'ŁAZ', 1, 8);
insert into areas values(23, 'INACTIVE', 'KCH', 2, 8);
insert into areas values(24, 'INACTIVE', 'KOR', 3, 8);
insert into areas values(25, 'INACTIVE', 'KOR', 1, 9);
insert into areas values(26, 'INACTIVE', 'ŁAZ', 2, 9);
insert into areas values(27, 'INACTIVE', 'KCH', 3, 9);
insert into areas values(28, 'INACTIVE', 'KCH', 1, 10);
insert into areas values(29, 'INACTIVE', 'KOR', 2, 10);
insert into areas values(30, 'INACTIVE', 'ŁAZ', 3, 10);
insert into areas values(31, 'INACTIVE', 'ŁAZ', 1, 11);
insert into areas values(32, 'INACTIVE', 'KCH', 2, 11);
insert into areas values(33, 'INACTIVE', 'KOR', 3, 11);
insert into areas values(34, 'INACTIVE', 'KOR', 1, 12);
insert into areas values(35, 'INACTIVE', 'ŁAZ', 2, 12);
insert into areas values(36, 'INACTIVE', 'KCH', 3, 12);
insert into areas values(37, 'INACTIVE', 'KCH', 1, 13);
insert into areas values(38, 'INACTIVE', 'KOR', 2, 13);
insert into areas values(39, 'INACTIVE', 'ŁAZ', 3, 13);

INSERT INTO ACTIVITIES VALUES(1,'UNDONE','ALWAYS','umyć wszystkie blaty',1);
INSERT INTO ACTIVITIES VALUES(2,'UNDONE','ALWAYS','umyć zlew + kran',1);
INSERT INTO ACTIVITIES VALUES(3,'UNDONE','ALWAYS','umyć palniki ',1);
INSERT INTO ACTIVITIES VALUES(4,'UNDONE','ALWAYS','umyć okap',1);
INSERT INTO ACTIVITIES VALUES(5,'UNDONE','EVEN','umyć swoje miejsca w szafkach',1);
INSERT INTO ACTIVITIES VALUES(6,'UNDONE','ALWAYS','umyć zewnętrzne miejsca na szafkach',1);
INSERT INTO ACTIVITIES VALUES(7,'UNDONE','EVEN','umyć górne miejsca na szafkach',1);
INSERT INTO ACTIVITIES VALUES(8,'UNDONE','ODD','umyc drzwiczki szafek',1);
INSERT INTO ACTIVITIES VALUES(9,'UNDONE','ALWAYS','umyć górę lodówki i bok',1);
INSERT INTO ACTIVITIES VALUES(10,'UNDONE','EVEN','umyć swoje miejsce w lodówce',1);
INSERT INTO ACTIVITIES VALUES(11,'UNDONE','EVEN','umyć okno',1);
INSERT INTO ACTIVITIES VALUES(12,'UNDONE','ODD','umyć piekarnik',1);
INSERT INTO ACTIVITIES VALUES(13,'UNDONE','ODD','umyć śmietnik',1);
INSERT INTO ACTIVITIES VALUES(14,'UNDONE','ALWAYS','odkurzenie podłogi korytarz+łazienka+kuchnia',2);
INSERT INTO ACTIVITIES VALUES(15,'UNDONE','ALWAYS','umycie podłogi korytarz+łazienka+kuchnia',2);
INSERT INTO ACTIVITIES VALUES(16,'UNDONE','EVEN','umycie drzwi wejściowych zewnątrz+wewnątrz',2);
INSERT INTO ACTIVITIES VALUES(17,'UNDONE','ODD','umycie lustra szafy',2);
INSERT INTO ACTIVITIES VALUES(18,'DONE','ALWAYS','umyć deskę i pokrywę',3);
INSERT INTO ACTIVITIES VALUES(19,'DONE','ALWAYS','umyć kibel zew+wew',3);
INSERT INTO ACTIVITIES VALUES(20,'DONE','ALWAYS','umyć szafkę na papier nad kiblem',3);
INSERT INTO ACTIVITIES VALUES(21,'DONE','ALWAYS','umyć szafki boczne drewniane z każdej strony',3);
INSERT INTO ACTIVITIES VALUES(22,'DONE','ALWAYS','umyć zlew i kran',3);
INSERT INTO ACTIVITIES VALUES(23,'DONE','ALWAYS','umyć szybkę szafki ',3);
INSERT INTO ACTIVITIES VALUES(24,'DONE','ALWAYS','umyć dół prysznica',3);
INSERT INTO ACTIVITIES VALUES(25,'DONE','ALWAYS','odszczelnić na 100% prysznic',3);
INSERT INTO ACTIVITIES VALUES(26,'DONE','ALWAYS','umyć swoją półkę w szafce',3);
INSERT INTO ACTIVITIES VALUES(27,'DONE','EVEN','umyć  słuchawke prysznica i trzymaki na szampony i mydło',3);
INSERT INTO ACTIVITIES VALUES(28,'DONE','ODD','umyć prowadnice kabiny',3);
INSERT INTO ACTIVITIES VALUES(29,'DONE','ODD','umyć szybkę kabiny',3);
INSERT INTO ACTIVITIES VALUES(30,'UNDONE','ALWAYS','umyć deskę i pokrywę',4);
INSERT INTO ACTIVITIES VALUES(31,'UNDONE','ALWAYS','umyć kibel zew+wew',4);
INSERT INTO ACTIVITIES VALUES(32,'UNDONE','ALWAYS','umyć szafkę na papier nad kiblem',4);
INSERT INTO ACTIVITIES VALUES(33,'UNDONE','ALWAYS','umyć szafki boczne drewniane z każdej strony',4);
INSERT INTO ACTIVITIES VALUES(34,'UNDONE','ALWAYS','umyć zlew i kran',4);
INSERT INTO ACTIVITIES VALUES(35,'UNDONE','ALWAYS','umyć szybkę szafki ',4);
INSERT INTO ACTIVITIES VALUES(36,'UNDONE','ALWAYS','umyć dół prysznica',4);
INSERT INTO ACTIVITIES VALUES(37,'UNDONE','ALWAYS','odszczelnić na 100% prysznic',4);
INSERT INTO ACTIVITIES VALUES(38,'UNDONE','ALWAYS','umyć swoją półkę w szafce',4);
INSERT INTO ACTIVITIES VALUES(39,'UNDONE','EVEN','umyć  słuchawke prysznica i trzymaki na szampony i mydło',4);
INSERT INTO ACTIVITIES VALUES(40,'UNDONE','ODD','umyć prowadnice kabiny',4);
INSERT INTO ACTIVITIES VALUES(41,'UNDONE','ODD','umyć szybkę kabiny',4);
INSERT INTO ACTIVITIES VALUES(42,'UNDONE','ALWAYS','umyć wszystkie blaty',5);
INSERT INTO ACTIVITIES VALUES(43,'UNDONE','ALWAYS','umyć zlew + kran',5);
INSERT INTO ACTIVITIES VALUES(44,'UNDONE','ALWAYS','umyć palniki ',5);
INSERT INTO ACTIVITIES VALUES(45,'UNDONE','ALWAYS','umyć okap',5);
INSERT INTO ACTIVITIES VALUES(46,'UNDONE','EVEN','umyć swoje miejsca w szafkach',5);
INSERT INTO ACTIVITIES VALUES(47,'UNDONE','ALWAYS','umyć zewnętrzne miejsca na szafkach',5);
INSERT INTO ACTIVITIES VALUES(48,'UNDONE','EVEN','umyć górne miejsca na szafkach',5);
INSERT INTO ACTIVITIES VALUES(49,'UNDONE','ODD','umyc drzwiczki szafek',5);
INSERT INTO ACTIVITIES VALUES(50,'UNDONE','ALWAYS','umyć górę lodówki i bok',5);
INSERT INTO ACTIVITIES VALUES(51,'UNDONE','EVEN','umyć swoje miejsce w lodówce',5);
INSERT INTO ACTIVITIES VALUES(52,'UNDONE','EVEN','umyć okno',5);
INSERT INTO ACTIVITIES VALUES(53,'UNDONE','ODD','umyć piekarnik',5);
INSERT INTO ACTIVITIES VALUES(54,'UNDONE','ODD','umyć śmietnik',5);
INSERT INTO ACTIVITIES VALUES(55,'UNDONE','ALWAYS','odkurzenie podłogi korytarz+łazienka+kuchnia',6);
INSERT INTO ACTIVITIES VALUES(56,'UNDONE','ALWAYS','umycie podłogi korytarz+łazienka+kuchnia',6);
INSERT INTO ACTIVITIES VALUES(57,'UNDONE','EVEN','umycie drzwi wejściowych zewnątrz+wewnątrz',6);
INSERT INTO ACTIVITIES VALUES(58,'UNDONE','ODD','umycie lustra szafy',6);
INSERT INTO ACTIVITIES VALUES(59,'UNDONE','ALWAYS','odkurzenie podłogi korytarz+łazienka+kuchnia',7);
INSERT INTO ACTIVITIES VALUES(60,'UNDONE','ALWAYS','umycie podłogi korytarz+łazienka+kuchnia',7);
INSERT INTO ACTIVITIES VALUES(61,'UNDONE','EVEN','umycie drzwi wejściowych zewnątrz+wewnątrz',7);
INSERT INTO ACTIVITIES VALUES(62,'UNDONE','ODD','umycie lustra szafy',7);
INSERT INTO ACTIVITIES VALUES(63,'UNDONE','ALWAYS','umyć deskę i pokrywę',8);
INSERT INTO ACTIVITIES VALUES(64,'UNDONE','ALWAYS','umyć kibel zew+wew',8);
INSERT INTO ACTIVITIES VALUES(65,'UNDONE','ALWAYS','umyć szafkę na papier nad kiblem',8);
INSERT INTO ACTIVITIES VALUES(66,'UNDONE','ALWAYS','umyć szafki boczne drewniane z każdej strony',8);
INSERT INTO ACTIVITIES VALUES(67,'UNDONE','ALWAYS','umyć zlew i kran',8);
INSERT INTO ACTIVITIES VALUES(68,'UNDONE','ALWAYS','umyć szybkę szafki ',8);
INSERT INTO ACTIVITIES VALUES(69,'UNDONE','ALWAYS','umyć dół prysznica',8);
INSERT INTO ACTIVITIES VALUES(70,'UNDONE','ALWAYS','odszczelnić na 100% prysznic',8);
INSERT INTO ACTIVITIES VALUES(71,'UNDONE','ALWAYS','umyć swoją półkę w szafce',8);
INSERT INTO ACTIVITIES VALUES(72,'UNDONE','EVEN','umyć  słuchawke prysznica i trzymaki na szampony i mydło',8);
INSERT INTO ACTIVITIES VALUES(73,'UNDONE','ODD','umyć prowadnice kabiny',8);
INSERT INTO ACTIVITIES VALUES(74,'UNDONE','ODD','umyć szybkę kabiny',8);
INSERT INTO ACTIVITIES VALUES(75,'UNDONE','ALWAYS','umyć wszystkie blaty',9);
INSERT INTO ACTIVITIES VALUES(76,'UNDONE','ALWAYS','umyć zlew + kran',9);
INSERT INTO ACTIVITIES VALUES(77,'UNDONE','ALWAYS','umyć palniki ',9);
INSERT INTO ACTIVITIES VALUES(78,'UNDONE','ALWAYS','umyć okap',9);
INSERT INTO ACTIVITIES VALUES(79,'UNDONE','EVEN','umyć swoje miejsca w szafkach',9);
INSERT INTO ACTIVITIES VALUES(80,'UNDONE','ALWAYS','umyć zewnętrzne miejsca na szafkach',9);
INSERT INTO ACTIVITIES VALUES(81,'UNDONE','EVEN','umyć górne miejsca na szafkach',9);
INSERT INTO ACTIVITIES VALUES(82,'UNDONE','ODD','umyc drzwiczki szafek',9);
INSERT INTO ACTIVITIES VALUES(83,'UNDONE','ALWAYS','umyć górę lodówki i bok',9);
INSERT INTO ACTIVITIES VALUES(84,'UNDONE','EVEN','umyć swoje miejsce w lodówce',9);
INSERT INTO ACTIVITIES VALUES(85,'UNDONE','EVEN','umyć okno',9);
INSERT INTO ACTIVITIES VALUES(86,'UNDONE','ODD','umyć piekarnik',9);
INSERT INTO ACTIVITIES VALUES(87,'UNDONE','ODD','umyć śmietnik',9);
INSERT INTO ACTIVITIES VALUES(88,'UNDONE','ALWAYS','umyć wszystkie blaty',10);
INSERT INTO ACTIVITIES VALUES(89,'UNDONE','ALWAYS','umyć zlew + kran',10);
INSERT INTO ACTIVITIES VALUES(90,'UNDONE','ALWAYS','umyć palniki ',10);
INSERT INTO ACTIVITIES VALUES(91,'UNDONE','ALWAYS','umyć okap',10);
INSERT INTO ACTIVITIES VALUES(92,'UNDONE','EVEN','umyć swoje miejsca w szafkach',10);
INSERT INTO ACTIVITIES VALUES(93,'UNDONE','ALWAYS','umyć zewnętrzne miejsca na szafkach',10);
INSERT INTO ACTIVITIES VALUES(94,'UNDONE','EVEN','umyć górne miejsca na szafkach',10);
INSERT INTO ACTIVITIES VALUES(95,'UNDONE','ODD','umyc drzwiczki szafek',10);
INSERT INTO ACTIVITIES VALUES(96,'UNDONE','ALWAYS','umyć górę lodówki i bok',10);
INSERT INTO ACTIVITIES VALUES(97,'UNDONE','EVEN','umyć swoje miejsce w lodówce',10);
INSERT INTO ACTIVITIES VALUES(98,'UNDONE','EVEN','umyć okno',10);
INSERT INTO ACTIVITIES VALUES(99,'UNDONE','ODD','umyć piekarnik',10);
INSERT INTO ACTIVITIES VALUES(100,'UNDONE','ODD','umyć śmietnik',10);
INSERT INTO ACTIVITIES VALUES(101,'UNDONE','ALWAYS','odkurzenie podłogi korytarz+łazienka+kuchnia',11);
INSERT INTO ACTIVITIES VALUES(102,'UNDONE','ALWAYS','umycie podłogi korytarz+łazienka+kuchnia',11);
INSERT INTO ACTIVITIES VALUES(103,'UNDONE','EVEN','umycie drzwi wejściowych zewnątrz+wewnątrz',11);
INSERT INTO ACTIVITIES VALUES(104,'UNDONE','ODD','umycie lustra szafy',11);
INSERT INTO ACTIVITIES VALUES(105,'UNDONE','ALWAYS','umyć deskę i pokrywę',12);
INSERT INTO ACTIVITIES VALUES(106,'UNDONE','ALWAYS','umyć kibel zew+wew',12);
INSERT INTO ACTIVITIES VALUES(107,'UNDONE','ALWAYS','umyć szafkę na papier nad kiblem',12);
INSERT INTO ACTIVITIES VALUES(108,'UNDONE','ALWAYS','umyć szafki boczne drewniane z każdej strony',12);
INSERT INTO ACTIVITIES VALUES(109,'UNDONE','ALWAYS','umyć zlew i kran',12);
INSERT INTO ACTIVITIES VALUES(110,'UNDONE','ALWAYS','umyć szybkę szafki ',12);
INSERT INTO ACTIVITIES VALUES(111,'UNDONE','ALWAYS','umyć dół prysznica',12);
INSERT INTO ACTIVITIES VALUES(112,'UNDONE','ALWAYS','odszczelnić na 100% prysznic',12);
INSERT INTO ACTIVITIES VALUES(113,'UNDONE','ALWAYS','umyć swoją półkę w szafce',12);
INSERT INTO ACTIVITIES VALUES(114,'UNDONE','EVEN','umyć  słuchawke prysznica i trzymaki na szampony i mydło',12);
INSERT INTO ACTIVITIES VALUES(115,'UNDONE','ODD','umyć prowadnice kabiny',12);
INSERT INTO ACTIVITIES VALUES(116,'UNDONE','ODD','umyć szybkę kabiny',12);
INSERT INTO ACTIVITIES VALUES(117,'UNDONE','ALWAYS','umyć deskę i pokrywę',13);
INSERT INTO ACTIVITIES VALUES(118,'UNDONE','ALWAYS','umyć kibel zew+wew',13);
INSERT INTO ACTIVITIES VALUES(119,'UNDONE','ALWAYS','umyć szafkę na papier nad kiblem',13);
INSERT INTO ACTIVITIES VALUES(120,'UNDONE','ALWAYS','umyć szafki boczne drewniane z każdej strony',13);
INSERT INTO ACTIVITIES VALUES(121,'UNDONE','ALWAYS','umyć zlew i kran',13);
INSERT INTO ACTIVITIES VALUES(122,'UNDONE','ALWAYS','umyć szybkę szafki ',13);
INSERT INTO ACTIVITIES VALUES(123,'UNDONE','ALWAYS','umyć dół prysznica',13);
INSERT INTO ACTIVITIES VALUES(124,'UNDONE','ALWAYS','odszczelnić na 100% prysznic',13);
INSERT INTO ACTIVITIES VALUES(125,'UNDONE','ALWAYS','umyć swoją półkę w szafce',13);
INSERT INTO ACTIVITIES VALUES(126,'UNDONE','EVEN','umyć  słuchawke prysznica i trzymaki na szampony i mydło',13);
INSERT INTO ACTIVITIES VALUES(127,'UNDONE','ODD','umyć prowadnice kabiny',13);
INSERT INTO ACTIVITIES VALUES(128,'UNDONE','ODD','umyć szybkę kabiny',13);
INSERT INTO ACTIVITIES VALUES(129,'UNDONE','ALWAYS','umyć wszystkie blaty',14);
INSERT INTO ACTIVITIES VALUES(130,'UNDONE','ALWAYS','umyć zlew + kran',14);
INSERT INTO ACTIVITIES VALUES(131,'UNDONE','ALWAYS','umyć palniki ',14);
INSERT INTO ACTIVITIES VALUES(132,'UNDONE','ALWAYS','umyć okap',14);
INSERT INTO ACTIVITIES VALUES(133,'UNDONE','EVEN','umyć swoje miejsca w szafkach',14);
INSERT INTO ACTIVITIES VALUES(134,'UNDONE','ALWAYS','umyć zewnętrzne miejsca na szafkach',14);
INSERT INTO ACTIVITIES VALUES(135,'UNDONE','EVEN','umyć górne miejsca na szafkach',14);
INSERT INTO ACTIVITIES VALUES(136,'UNDONE','ODD','umyc drzwiczki szafek',14);
INSERT INTO ACTIVITIES VALUES(137,'UNDONE','ALWAYS','umyć górę lodówki i bok',14);
INSERT INTO ACTIVITIES VALUES(138,'UNDONE','EVEN','umyć swoje miejsce w lodówce',14);
INSERT INTO ACTIVITIES VALUES(139,'UNDONE','EVEN','umyć okno',14);
INSERT INTO ACTIVITIES VALUES(140,'UNDONE','ODD','umyć piekarnik',14);
INSERT INTO ACTIVITIES VALUES(141,'UNDONE','ODD','umyć śmietnik',14);
INSERT INTO ACTIVITIES VALUES(142,'UNDONE','ALWAYS','odkurzenie podłogi korytarz+łazienka+kuchnia',15);
INSERT INTO ACTIVITIES VALUES(143,'UNDONE','ALWAYS','umycie podłogi korytarz+łazienka+kuchnia',15);
INSERT INTO ACTIVITIES VALUES(144,'UNDONE','EVEN','umycie drzwi wejściowych zewnątrz+wewnątrz',15);
INSERT INTO ACTIVITIES VALUES(145,'UNDONE','ODD','umycie lustra szafy',15);
INSERT INTO ACTIVITIES VALUES(146,'UNDONE','ALWAYS','odkurzenie podłogi korytarz+łazienka+kuchnia',16);
INSERT INTO ACTIVITIES VALUES(147,'UNDONE','ALWAYS','umycie podłogi korytarz+łazienka+kuchnia',16);
INSERT INTO ACTIVITIES VALUES(148,'UNDONE','EVEN','umycie drzwi wejściowych zewnątrz+wewnątrz',16);
INSERT INTO ACTIVITIES VALUES(149,'UNDONE','ODD','umycie lustra szafy',16);
INSERT INTO ACTIVITIES VALUES(150,'UNDONE','ALWAYS','umyć deskę i pokrywę',17);
INSERT INTO ACTIVITIES VALUES(151,'UNDONE','ALWAYS','umyć kibel zew+wew',17);
INSERT INTO ACTIVITIES VALUES(152,'UNDONE','ALWAYS','umyć szafkę na papier nad kiblem',17);
INSERT INTO ACTIVITIES VALUES(153,'UNDONE','ALWAYS','umyć szafki boczne drewniane z każdej strony',17);
INSERT INTO ACTIVITIES VALUES(154,'UNDONE','ALWAYS','umyć zlew i kran',17);
INSERT INTO ACTIVITIES VALUES(155,'UNDONE','ALWAYS','umyć szybkę szafki ',17);
INSERT INTO ACTIVITIES VALUES(156,'UNDONE','ALWAYS','umyć dół prysznica',17);
INSERT INTO ACTIVITIES VALUES(157,'UNDONE','ALWAYS','odszczelnić na 100% prysznic',17);
INSERT INTO ACTIVITIES VALUES(158,'UNDONE','ALWAYS','umyć swoją półkę w szafce',17);
INSERT INTO ACTIVITIES VALUES(159,'UNDONE','EVEN','umyć  słuchawke prysznica i trzymaki na szampony i mydło',17);
INSERT INTO ACTIVITIES VALUES(160,'UNDONE','ODD','umyć prowadnice kabiny',17);
INSERT INTO ACTIVITIES VALUES(161,'UNDONE','ODD','umyć szybkę kabiny',17);
INSERT INTO ACTIVITIES VALUES(162,'UNDONE','ALWAYS','umyć wszystkie blaty',18);
INSERT INTO ACTIVITIES VALUES(163,'UNDONE','ALWAYS','umyć zlew + kran',18);
INSERT INTO ACTIVITIES VALUES(164,'UNDONE','ALWAYS','umyć palniki ',18);
INSERT INTO ACTIVITIES VALUES(165,'UNDONE','ALWAYS','umyć okap',18);
INSERT INTO ACTIVITIES VALUES(166,'UNDONE','EVEN','umyć swoje miejsca w szafkach',18);
INSERT INTO ACTIVITIES VALUES(167,'UNDONE','ALWAYS','umyć zewnętrzne miejsca na szafkach',18);
INSERT INTO ACTIVITIES VALUES(168,'UNDONE','EVEN','umyć górne miejsca na szafkach',18);
INSERT INTO ACTIVITIES VALUES(169,'UNDONE','ODD','umyc drzwiczki szafek',18);
INSERT INTO ACTIVITIES VALUES(170,'UNDONE','ALWAYS','umyć górę lodówki i bok',18);
INSERT INTO ACTIVITIES VALUES(171,'UNDONE','EVEN','umyć swoje miejsce w lodówce',18);
INSERT INTO ACTIVITIES VALUES(172,'UNDONE','EVEN','umyć okno',18);
INSERT INTO ACTIVITIES VALUES(173,'UNDONE','ODD','umyć piekarnik',18);
INSERT INTO ACTIVITIES VALUES(174,'UNDONE','ODD','umyć śmietnik',18);
INSERT INTO ACTIVITIES VALUES(175,'UNDONE','ALWAYS','umyć wszystkie blaty',19);
INSERT INTO ACTIVITIES VALUES(176,'UNDONE','ALWAYS','umyć zlew + kran',19);
INSERT INTO ACTIVITIES VALUES(177,'UNDONE','ALWAYS','umyć palniki ',19);
INSERT INTO ACTIVITIES VALUES(178,'UNDONE','ALWAYS','umyć okap',19);
INSERT INTO ACTIVITIES VALUES(179,'UNDONE','EVEN','umyć swoje miejsca w szafkach',19);
INSERT INTO ACTIVITIES VALUES(180,'UNDONE','ALWAYS','umyć zewnętrzne miejsca na szafkach',19);
INSERT INTO ACTIVITIES VALUES(181,'UNDONE','EVEN','umyć górne miejsca na szafkach',19);
INSERT INTO ACTIVITIES VALUES(182,'UNDONE','ODD','umyc drzwiczki szafek',19);
INSERT INTO ACTIVITIES VALUES(183,'UNDONE','ALWAYS','umyć górę lodówki i bok',19);
INSERT INTO ACTIVITIES VALUES(184,'UNDONE','EVEN','umyć swoje miejsce w lodówce',19);
INSERT INTO ACTIVITIES VALUES(185,'UNDONE','EVEN','umyć okno',19);
INSERT INTO ACTIVITIES VALUES(186,'UNDONE','ODD','umyć piekarnik',19);
INSERT INTO ACTIVITIES VALUES(187,'UNDONE','ODD','umyć śmietnik',19);
INSERT INTO ACTIVITIES VALUES(188,'UNDONE','ALWAYS','odkurzenie podłogi korytarz+łazienka+kuchnia',20);
INSERT INTO ACTIVITIES VALUES(189,'UNDONE','ALWAYS','umycie podłogi korytarz+łazienka+kuchnia',20);
INSERT INTO ACTIVITIES VALUES(190,'UNDONE','EVEN','umycie drzwi wejściowych zewnątrz+wewnątrz',20);
INSERT INTO ACTIVITIES VALUES(191,'UNDONE','ODD','umycie lustra szafy',20);
INSERT INTO ACTIVITIES VALUES(192,'UNDONE','ALWAYS','umyć deskę i pokrywę',21);
INSERT INTO ACTIVITIES VALUES(193,'UNDONE','ALWAYS','umyć kibel zew+wew',21);
INSERT INTO ACTIVITIES VALUES(194,'UNDONE','ALWAYS','umyć szafkę na papier nad kiblem',21);
INSERT INTO ACTIVITIES VALUES(195,'UNDONE','ALWAYS','umyć szafki boczne drewniane z każdej strony',21);
INSERT INTO ACTIVITIES VALUES(196,'UNDONE','ALWAYS','umyć zlew i kran',21);
INSERT INTO ACTIVITIES VALUES(197,'UNDONE','ALWAYS','umyć szybkę szafki ',21);
INSERT INTO ACTIVITIES VALUES(198,'UNDONE','ALWAYS','umyć dół prysznica',21);
INSERT INTO ACTIVITIES VALUES(199,'UNDONE','ALWAYS','odszczelnić na 100% prysznic',21);
INSERT INTO ACTIVITIES VALUES(200,'UNDONE','ALWAYS','umyć swoją półkę w szafce',21);
INSERT INTO ACTIVITIES VALUES(201,'UNDONE','EVEN','umyć  słuchawke prysznica i trzymaki na szampony i mydło',21);
INSERT INTO ACTIVITIES VALUES(202,'UNDONE','ODD','umyć prowadnice kabiny',21);
INSERT INTO ACTIVITIES VALUES(203,'UNDONE','ODD','umyć szybkę kabiny',21);
INSERT INTO ACTIVITIES VALUES(204,'UNDONE','ALWAYS','umyć deskę i pokrywę',22);
INSERT INTO ACTIVITIES VALUES(205,'UNDONE','ALWAYS','umyć kibel zew+wew',22);
INSERT INTO ACTIVITIES VALUES(206,'UNDONE','ALWAYS','umyć szafkę na papier nad kiblem',22);
INSERT INTO ACTIVITIES VALUES(207,'UNDONE','ALWAYS','umyć szafki boczne drewniane z każdej strony',22);
INSERT INTO ACTIVITIES VALUES(208,'UNDONE','ALWAYS','umyć zlew i kran',22);
INSERT INTO ACTIVITIES VALUES(209,'UNDONE','ALWAYS','umyć szybkę szafki ',22);
INSERT INTO ACTIVITIES VALUES(210,'UNDONE','ALWAYS','umyć dół prysznica',22);
INSERT INTO ACTIVITIES VALUES(211,'UNDONE','ALWAYS','odszczelnić na 100% prysznic',22);
INSERT INTO ACTIVITIES VALUES(212,'UNDONE','ALWAYS','umyć swoją półkę w szafce',22);
INSERT INTO ACTIVITIES VALUES(213,'UNDONE','EVEN','umyć  słuchawke prysznica i trzymaki na szampony i mydło',22);
INSERT INTO ACTIVITIES VALUES(214,'UNDONE','ODD','umyć prowadnice kabiny',22);
INSERT INTO ACTIVITIES VALUES(215,'UNDONE','ODD','umyć szybkę kabiny',22);
INSERT INTO ACTIVITIES VALUES(216,'UNDONE','ALWAYS','umyć wszystkie blaty',23);
INSERT INTO ACTIVITIES VALUES(217,'UNDONE','ALWAYS','umyć zlew + kran',23);
INSERT INTO ACTIVITIES VALUES(218,'UNDONE','ALWAYS','umyć palniki ',23);
INSERT INTO ACTIVITIES VALUES(219,'UNDONE','ALWAYS','umyć okap',23);
INSERT INTO ACTIVITIES VALUES(220,'UNDONE','EVEN','umyć swoje miejsca w szafkach',23);
INSERT INTO ACTIVITIES VALUES(221,'UNDONE','ALWAYS','umyć zewnętrzne miejsca na szafkach',23);
INSERT INTO ACTIVITIES VALUES(222,'UNDONE','EVEN','umyć górne miejsca na szafkach',23);
INSERT INTO ACTIVITIES VALUES(223,'UNDONE','ODD','umyc drzwiczki szafek',23);
INSERT INTO ACTIVITIES VALUES(224,'UNDONE','ALWAYS','umyć górę lodówki i bok',23);
INSERT INTO ACTIVITIES VALUES(225,'UNDONE','EVEN','umyć swoje miejsce w lodówce',23);
INSERT INTO ACTIVITIES VALUES(226,'UNDONE','EVEN','umyć okno',23);
INSERT INTO ACTIVITIES VALUES(227,'UNDONE','ODD','umyć piekarnik',23);
INSERT INTO ACTIVITIES VALUES(228,'UNDONE','ODD','umyć śmietnik',23);
INSERT INTO ACTIVITIES VALUES(229,'UNDONE','ALWAYS','odkurzenie podłogi korytarz+łazienka+kuchnia',24);
INSERT INTO ACTIVITIES VALUES(230,'UNDONE','ALWAYS','umycie podłogi korytarz+łazienka+kuchnia',24);
INSERT INTO ACTIVITIES VALUES(231,'UNDONE','EVEN','umycie drzwi wejściowych zewnątrz+wewnątrz',24);
INSERT INTO ACTIVITIES VALUES(232,'UNDONE','ODD','umycie lustra szafy',24);
INSERT INTO ACTIVITIES VALUES(233,'UNDONE','ALWAYS','odkurzenie podłogi korytarz+łazienka+kuchnia',25);
INSERT INTO ACTIVITIES VALUES(234,'UNDONE','ALWAYS','umycie podłogi korytarz+łazienka+kuchnia',25);
INSERT INTO ACTIVITIES VALUES(235,'UNDONE','EVEN','umycie drzwi wejściowych zewnątrz+wewnątrz',25);
INSERT INTO ACTIVITIES VALUES(236,'UNDONE','ODD','umycie lustra szafy',25);
INSERT INTO ACTIVITIES VALUES(237,'UNDONE','ALWAYS','umyć deskę i pokrywę',26);
INSERT INTO ACTIVITIES VALUES(238,'UNDONE','ALWAYS','umyć kibel zew+wew',26);
INSERT INTO ACTIVITIES VALUES(239,'UNDONE','ALWAYS','umyć szafkę na papier nad kiblem',26);
INSERT INTO ACTIVITIES VALUES(240,'UNDONE','ALWAYS','umyć szafki boczne drewniane z każdej strony',26);
INSERT INTO ACTIVITIES VALUES(241,'UNDONE','ALWAYS','umyć zlew i kran',26);
INSERT INTO ACTIVITIES VALUES(242,'UNDONE','ALWAYS','umyć szybkę szafki ',26);
INSERT INTO ACTIVITIES VALUES(243,'UNDONE','ALWAYS','umyć dół prysznica',26);
INSERT INTO ACTIVITIES VALUES(244,'UNDONE','ALWAYS','odszczelnić na 100% prysznic',26);
INSERT INTO ACTIVITIES VALUES(245,'UNDONE','ALWAYS','umyć swoją półkę w szafce',26);
INSERT INTO ACTIVITIES VALUES(246,'UNDONE','EVEN','umyć  słuchawke prysznica i trzymaki na szampony i mydło',26);
INSERT INTO ACTIVITIES VALUES(247,'UNDONE','ODD','umyć prowadnice kabiny',26);
INSERT INTO ACTIVITIES VALUES(248,'UNDONE','ODD','umyć szybkę kabiny',26);
INSERT INTO ACTIVITIES VALUES(249,'UNDONE','ALWAYS','umyć wszystkie blaty',27);
INSERT INTO ACTIVITIES VALUES(250,'UNDONE','ALWAYS','umyć zlew + kran',27);
INSERT INTO ACTIVITIES VALUES(251,'UNDONE','ALWAYS','umyć palniki ',27);
INSERT INTO ACTIVITIES VALUES(252,'UNDONE','ALWAYS','umyć okap',27);
INSERT INTO ACTIVITIES VALUES(253,'UNDONE','EVEN','umyć swoje miejsca w szafkach',27);
INSERT INTO ACTIVITIES VALUES(254,'UNDONE','ALWAYS','umyć zewnętrzne miejsca na szafkach',27);
INSERT INTO ACTIVITIES VALUES(255,'UNDONE','EVEN','umyć górne miejsca na szafkach',27);
INSERT INTO ACTIVITIES VALUES(256,'UNDONE','ODD','umyc drzwiczki szafek',27);
INSERT INTO ACTIVITIES VALUES(257,'UNDONE','ALWAYS','umyć górę lodówki i bok',27);
INSERT INTO ACTIVITIES VALUES(258,'UNDONE','EVEN','umyć swoje miejsce w lodówce',27);
INSERT INTO ACTIVITIES VALUES(259,'UNDONE','EVEN','umyć okno',27);
INSERT INTO ACTIVITIES VALUES(260,'UNDONE','ODD','umyć piekarnik',27);
INSERT INTO ACTIVITIES VALUES(261,'UNDONE','ODD','umyć śmietnik',27);
INSERT INTO ACTIVITIES VALUES(262,'UNDONE','ALWAYS','umyć wszystkie blaty',28);
INSERT INTO ACTIVITIES VALUES(263,'UNDONE','ALWAYS','umyć zlew + kran',28);
INSERT INTO ACTIVITIES VALUES(264,'UNDONE','ALWAYS','umyć palniki ',28);
INSERT INTO ACTIVITIES VALUES(265,'UNDONE','ALWAYS','umyć okap',28);
INSERT INTO ACTIVITIES VALUES(266,'UNDONE','EVEN','umyć swoje miejsca w szafkach',28);
INSERT INTO ACTIVITIES VALUES(267,'UNDONE','ALWAYS','umyć zewnętrzne miejsca na szafkach',28);
INSERT INTO ACTIVITIES VALUES(268,'UNDONE','EVEN','umyć górne miejsca na szafkach',28);
INSERT INTO ACTIVITIES VALUES(269,'UNDONE','ODD','umyc drzwiczki szafek',28);
INSERT INTO ACTIVITIES VALUES(270,'UNDONE','ALWAYS','umyć górę lodówki i bok',28);
INSERT INTO ACTIVITIES VALUES(271,'UNDONE','EVEN','umyć swoje miejsce w lodówce',28);
INSERT INTO ACTIVITIES VALUES(272,'UNDONE','EVEN','umyć okno',28);
INSERT INTO ACTIVITIES VALUES(273,'UNDONE','ODD','umyć piekarnik',28);
INSERT INTO ACTIVITIES VALUES(274,'UNDONE','ODD','umyć śmietnik',28);
INSERT INTO ACTIVITIES VALUES(275,'UNDONE','ALWAYS','odkurzenie podłogi korytarz+łazienka+kuchnia',29);
INSERT INTO ACTIVITIES VALUES(276,'UNDONE','ALWAYS','umycie podłogi korytarz+łazienka+kuchnia',29);
INSERT INTO ACTIVITIES VALUES(277,'UNDONE','EVEN','umycie drzwi wejściowych zewnątrz+wewnątrz',29);
INSERT INTO ACTIVITIES VALUES(278,'UNDONE','ODD','umycie lustra szafy',29);
INSERT INTO ACTIVITIES VALUES(279,'UNDONE','ALWAYS','umyć deskę i pokrywę',30);
INSERT INTO ACTIVITIES VALUES(280,'UNDONE','ALWAYS','umyć kibel zew+wew',30);
INSERT INTO ACTIVITIES VALUES(281,'UNDONE','ALWAYS','umyć szafkę na papier nad kiblem',30);
INSERT INTO ACTIVITIES VALUES(282,'UNDONE','ALWAYS','umyć szafki boczne drewniane z każdej strony',30);
INSERT INTO ACTIVITIES VALUES(283,'UNDONE','ALWAYS','umyć zlew i kran',30);
INSERT INTO ACTIVITIES VALUES(284,'UNDONE','ALWAYS','umyć szybkę szafki ',30);
INSERT INTO ACTIVITIES VALUES(285,'UNDONE','ALWAYS','umyć dół prysznica',30);
INSERT INTO ACTIVITIES VALUES(286,'UNDONE','ALWAYS','odszczelnić na 100% prysznic',30);
INSERT INTO ACTIVITIES VALUES(287,'UNDONE','ALWAYS','umyć swoją półkę w szafce',30);
INSERT INTO ACTIVITIES VALUES(288,'UNDONE','EVEN','umyć  słuchawke prysznica i trzymaki na szampony i mydło',30);
INSERT INTO ACTIVITIES VALUES(289,'UNDONE','ODD','umyć prowadnice kabiny',30);
INSERT INTO ACTIVITIES VALUES(290,'UNDONE','ODD','umyć szybkę kabiny',30);
INSERT INTO ACTIVITIES VALUES(291,'UNDONE','ALWAYS','umyć deskę i pokrywę',31);
INSERT INTO ACTIVITIES VALUES(292,'UNDONE','ALWAYS','umyć kibel zew+wew',31);
INSERT INTO ACTIVITIES VALUES(293,'UNDONE','ALWAYS','umyć szafkę na papier nad kiblem',31);
INSERT INTO ACTIVITIES VALUES(294,'UNDONE','ALWAYS','umyć szafki boczne drewniane z każdej strony',31);
INSERT INTO ACTIVITIES VALUES(295,'UNDONE','ALWAYS','umyć zlew i kran',31);
INSERT INTO ACTIVITIES VALUES(296,'UNDONE','ALWAYS','umyć szybkę szafki ',31);
INSERT INTO ACTIVITIES VALUES(297,'UNDONE','ALWAYS','umyć dół prysznica',31);
INSERT INTO ACTIVITIES VALUES(298,'UNDONE','ALWAYS','odszczelnić na 100% prysznic',31);
INSERT INTO ACTIVITIES VALUES(299,'UNDONE','ALWAYS','umyć swoją półkę w szafce',31);
INSERT INTO ACTIVITIES VALUES(300,'UNDONE','EVEN','umyć  słuchawke prysznica i trzymaki na szampony i mydło',31);
INSERT INTO ACTIVITIES VALUES(301,'UNDONE','ODD','umyć prowadnice kabiny',31);
INSERT INTO ACTIVITIES VALUES(302,'UNDONE','ODD','umyć szybkę kabiny',31);
INSERT INTO ACTIVITIES VALUES(303,'UNDONE','ALWAYS','umyć wszystkie blaty',32);
INSERT INTO ACTIVITIES VALUES(304,'UNDONE','ALWAYS','umyć zlew + kran',32);
INSERT INTO ACTIVITIES VALUES(305,'UNDONE','ALWAYS','umyć palniki ',32);
INSERT INTO ACTIVITIES VALUES(306,'UNDONE','ALWAYS','umyć okap',32);
INSERT INTO ACTIVITIES VALUES(307,'UNDONE','EVEN','umyć swoje miejsca w szafkach',32);
INSERT INTO ACTIVITIES VALUES(308,'UNDONE','ALWAYS','umyć zewnętrzne miejsca na szafkach',32);
INSERT INTO ACTIVITIES VALUES(309,'UNDONE','EVEN','umyć górne miejsca na szafkach',32);
INSERT INTO ACTIVITIES VALUES(310,'UNDONE','ODD','umyc drzwiczki szafek',32);
INSERT INTO ACTIVITIES VALUES(311,'UNDONE','ALWAYS','umyć górę lodówki i bok',32);
INSERT INTO ACTIVITIES VALUES(312,'UNDONE','EVEN','umyć swoje miejsce w lodówce',32);
INSERT INTO ACTIVITIES VALUES(313,'UNDONE','EVEN','umyć okno',32);
INSERT INTO ACTIVITIES VALUES(314,'UNDONE','ODD','umyć piekarnik',32);
INSERT INTO ACTIVITIES VALUES(315,'UNDONE','ODD','umyć śmietnik',32);
INSERT INTO ACTIVITIES VALUES(316,'UNDONE','ALWAYS','odkurzenie podłogi korytarz+łazienka+kuchnia',33);
INSERT INTO ACTIVITIES VALUES(317,'UNDONE','ALWAYS','umycie podłogi korytarz+łazienka+kuchnia',33);
INSERT INTO ACTIVITIES VALUES(318,'UNDONE','EVEN','umycie drzwi wejściowych zewnątrz+wewnątrz',33);
INSERT INTO ACTIVITIES VALUES(319,'UNDONE','ODD','umycie lustra szafy',33);
INSERT INTO ACTIVITIES VALUES(320,'UNDONE','ALWAYS','odkurzenie podłogi korytarz+łazienka+kuchnia',34);
INSERT INTO ACTIVITIES VALUES(321,'UNDONE','ALWAYS','umycie podłogi korytarz+łazienka+kuchnia',34);
INSERT INTO ACTIVITIES VALUES(322,'UNDONE','EVEN','umycie drzwi wejściowych zewnątrz+wewnątrz',34);
INSERT INTO ACTIVITIES VALUES(323,'UNDONE','ODD','umycie lustra szafy',34);
INSERT INTO ACTIVITIES VALUES(324,'UNDONE','ALWAYS','umyć deskę i pokrywę',35);
INSERT INTO ACTIVITIES VALUES(325,'UNDONE','ALWAYS','umyć kibel zew+wew',35);
INSERT INTO ACTIVITIES VALUES(326,'UNDONE','ALWAYS','umyć szafkę na papier nad kiblem',35);
INSERT INTO ACTIVITIES VALUES(327,'UNDONE','ALWAYS','umyć szafki boczne drewniane z każdej strony',35);
INSERT INTO ACTIVITIES VALUES(328,'UNDONE','ALWAYS','umyć zlew i kran',35);
INSERT INTO ACTIVITIES VALUES(329,'UNDONE','ALWAYS','umyć szybkę szafki ',35);
INSERT INTO ACTIVITIES VALUES(330,'UNDONE','ALWAYS','umyć dół prysznica',35);
INSERT INTO ACTIVITIES VALUES(331,'UNDONE','ALWAYS','odszczelnić na 100% prysznic',35);
INSERT INTO ACTIVITIES VALUES(332,'UNDONE','ALWAYS','umyć swoją półkę w szafce',35);
INSERT INTO ACTIVITIES VALUES(333,'UNDONE','EVEN','umyć  słuchawke prysznica i trzymaki na szampony i mydło',35);
INSERT INTO ACTIVITIES VALUES(334,'UNDONE','ODD','umyć prowadnice kabiny',35);
INSERT INTO ACTIVITIES VALUES(335,'UNDONE','ODD','umyć szybkę kabiny',35);
INSERT INTO ACTIVITIES VALUES(336,'UNDONE','ALWAYS','umyć wszystkie blaty',36);
INSERT INTO ACTIVITIES VALUES(337,'UNDONE','ALWAYS','umyć zlew + kran',36);
INSERT INTO ACTIVITIES VALUES(338,'UNDONE','ALWAYS','umyć palniki ',36);
INSERT INTO ACTIVITIES VALUES(339,'UNDONE','ALWAYS','umyć okap',36);
INSERT INTO ACTIVITIES VALUES(340,'UNDONE','EVEN','umyć swoje miejsca w szafkach',36);
INSERT INTO ACTIVITIES VALUES(341,'UNDONE','ALWAYS','umyć zewnętrzne miejsca na szafkach',36);
INSERT INTO ACTIVITIES VALUES(342,'UNDONE','EVEN','umyć górne miejsca na szafkach',36);
INSERT INTO ACTIVITIES VALUES(343,'UNDONE','ODD','umyc drzwiczki szafek',36);
INSERT INTO ACTIVITIES VALUES(344,'UNDONE','ALWAYS','umyć górę lodówki i bok',36);
INSERT INTO ACTIVITIES VALUES(345,'UNDONE','EVEN','umyć swoje miejsce w lodówce',36);
INSERT INTO ACTIVITIES VALUES(346,'UNDONE','EVEN','umyć okno',36);
INSERT INTO ACTIVITIES VALUES(347,'UNDONE','ODD','umyć piekarnik',36);
INSERT INTO ACTIVITIES VALUES(348,'UNDONE','ODD','umyć śmietnik',36);
INSERT INTO ACTIVITIES VALUES(349,'UNDONE','ALWAYS','umyć wszystkie blaty',37);
INSERT INTO ACTIVITIES VALUES(350,'UNDONE','ALWAYS','umyć zlew + kran',37);
INSERT INTO ACTIVITIES VALUES(351,'UNDONE','ALWAYS','umyć palniki ',37);
INSERT INTO ACTIVITIES VALUES(352,'UNDONE','ALWAYS','umyć okap',37);
INSERT INTO ACTIVITIES VALUES(353,'UNDONE','EVEN','umyć swoje miejsca w szafkach',37);
INSERT INTO ACTIVITIES VALUES(354,'UNDONE','ALWAYS','umyć zewnętrzne miejsca na szafkach',37);
INSERT INTO ACTIVITIES VALUES(355,'UNDONE','EVEN','umyć górne miejsca na szafkach',37);
INSERT INTO ACTIVITIES VALUES(356,'UNDONE','ODD','umyc drzwiczki szafek',37);
INSERT INTO ACTIVITIES VALUES(357,'UNDONE','ALWAYS','umyć górę lodówki i bok',37);
INSERT INTO ACTIVITIES VALUES(358,'UNDONE','EVEN','umyć swoje miejsce w lodówce',37);
INSERT INTO ACTIVITIES VALUES(359,'UNDONE','EVEN','umyć okno',37);
INSERT INTO ACTIVITIES VALUES(360,'UNDONE','ODD','umyć piekarnik',37);
INSERT INTO ACTIVITIES VALUES(361,'UNDONE','ODD','umyć śmietnik',37);
INSERT INTO ACTIVITIES VALUES(362,'UNDONE','ALWAYS','odkurzenie podłogi korytarz+łazienka+kuchnia',38);
INSERT INTO ACTIVITIES VALUES(363,'UNDONE','ALWAYS','umycie podłogi korytarz+łazienka+kuchnia',38);
INSERT INTO ACTIVITIES VALUES(364,'UNDONE','EVEN','umycie drzwi wejściowych zewnątrz+wewnątrz',38);
INSERT INTO ACTIVITIES VALUES(365,'UNDONE','ODD','umycie lustra szafy',38);
INSERT INTO ACTIVITIES VALUES(366,'UNDONE','ALWAYS','umyć deskę i pokrywę',39);
INSERT INTO ACTIVITIES VALUES(367,'UNDONE','ALWAYS','umyć kibel zew+wew',39);
INSERT INTO ACTIVITIES VALUES(368,'UNDONE','ALWAYS','umyć szafkę na papier nad kiblem',39);
INSERT INTO ACTIVITIES VALUES(369,'UNDONE','ALWAYS','umyć szafki boczne drewniane z każdej strony',39);
INSERT INTO ACTIVITIES VALUES(370,'UNDONE','ALWAYS','umyć zlew i kran',39);
INSERT INTO ACTIVITIES VALUES(371,'UNDONE','ALWAYS','umyć szybkę szafki ',39);
INSERT INTO ACTIVITIES VALUES(372,'UNDONE','ALWAYS','umyć dół prysznica',39);
INSERT INTO ACTIVITIES VALUES(373,'UNDONE','ALWAYS','odszczelnić na 100% prysznic',39);
INSERT INTO ACTIVITIES VALUES(374,'UNDONE','ALWAYS','umyć swoją półkę w szafce',39);
INSERT INTO ACTIVITIES VALUES(375,'UNDONE','EVEN','umyć  słuchawke prysznica i trzymaki na szampony i mydło',39);
INSERT INTO ACTIVITIES VALUES(376,'UNDONE','ODD','umyć prowadnice kabiny',39);
INSERT INTO ACTIVITIES VALUES(377,'UNDONE','ODD','umyć szybkę kabiny',39);




